version: '3.8'

name: sa_usecase_1_mysql

services:
  my_source:
    container_name: my_source
    image: mysql:8
    restart: always
    command:
      - "mysqld"
      - "--server-id=1"
      - "--log-bin=mysql-bin"
      - "--log-error-verbosity=8"
    ports:
      - "33100:3306"
    volumes:
      - data_dir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kla1sdALKS4354DJa768klsdals41j1dkljas7DASDk4ll3ajs8dlASD
      - MYSQL_USER=nkhartwig
      - MYSQL_PASSWORD=tmp
      - MYSQL_DATABASE=db
    networks:
      - mysql_replication

      
  my_replica_1:
    container_name: my_replica_1
    image: mysql:8
    restart: always
    command:
      - "mysqld"
      - "--server-id=2"
      - "--log-bin=mysql-bin"
      - "--log-error-verbosity=8"
    ports:
      - "33101:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kla1sdALKS4354DJa768klsdals41j1dkljas7DASDk4ll3ajs8dlASD
      - MYSQL_USER=nkhartwig
      - MYSQL_PASSWORD=tmp
      - MYSQL_DATABASE=db
    depends_on:
      - my_source
    networks:
      - mysql_replication
      

  my_replica_2:
    container_name: my_replica_2
    image: mysql:8
    restart: always
    command:
      - "mysqld"
      - "--server-id=3"
      - "--log-bin=mysql-bin"
    ports:
      - "33102:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kla1sdALKS4354DJa768klsdals41j1dkljas7DASDk4ll3ajs8dlASD
      - MYSQL_USER=nkhartwig
      - MYSQL_PASSWORD=tmp
      - MYSQL_DATABASE=db
    depends_on:
      - my_source
    networks:
      - mysql_replication
  

  my_replica_3:
    container_name: my_replica_3
    image: mysql:8
    restart: always
    command:
      - "mysqld"
      - "--server-id=4"
      - "--log-bin=mysql-bin"
    ports:
      - "33103:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kla1sdALKS4354DJa768klsdals41j1dkljas7DASDk4ll3ajs8dlASD
      - MYSQL_USER=nkhartwig
      - MYSQL_PASSWORD=tmp
      - MYSQL_DATABASE=db
    depends_on:
      - my_source
    networks:
      - mysql_replication

  
  configure:
    container_name: configure_replication_script
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./configure_replication.py:/app/main.py
      - ./dumps:/dumps
    links:
      - my_source:master_db
      - my_replica_1:slave_1_db
      - my_replica_2:slave_2_db
      - my_replica_3:slave_3_db
    profiles:
      - donotstart
    networks:
      - mysql_replication

  
  my_pma:
    container_name: my_pma
    image: phpmyadmin:5.2
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - my_source
    links:
      - my_source:db
    environment:
      - UPLOAD_LIMIT=1G
    networks:
      - mysql_replication
    profiles:
      - donotstart
    
volumes:
  data_dir:

networks:
  mysql_replication: