
FROM ubuntu:22.04


RUN apt update
RUN apt install -y --no-install-recommends mysql-client
RUN apt install -y --no-install-recommends python3
RUN apt install -y --no-install-recommends python3-pip

# Test installation
RUN mysqldump --version
RUN python3 --version
RUN pip3 --version

RUN pip3 install mysql-connector-python

CMD python3 /app/main.py