version: '3.8'

name: sa_usecase_1_mysql

services:
  my_source:
    container_name: my_source
    image: mysql:8
    command:
      - "mysqld"
      - "--server-id=1"
      - "--log-bin=mysql-bin"
      - "--log-error-verbosity=8"
    ports:
      - "33100:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kla1sdALKS4354DJa768klsdals41j1dkljas7DASDk4ll3ajs8dlASD
      - MYSQL_USER=sa_uc_1
      - MYSQL_PASSWORD=sa_uc_1_password
      - MYSQL_DATABASE=db
    networks:
      - mysql_replication

      
  my_replica:
    container_name: my_replica
    image: mysql:8
    command:
      - "mysqld"
      - "--server-id=2"
      - "--log-slave-updates"
      - "--log-bin=mysql-bin"
      - "--log-error-verbosity=8"
    ports:
      - "33101:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kla1sdALKS4354DJa768klsdals41j1dkljas7DASDk4ll3ajs8dlASD
      - MYSQL_USER=sa_uc_1
      - MYSQL_PASSWORD=sa_uc_1_password
      - MYSQL_DATABASE=db
    depends_on:
      - my_source
    networks:
      - mysql_replication

  
  configure:
    container_name: configure_replication_script
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./configure_replication.py:/app/main.py
    links:
      - my_source:master_db
      - my_replica:slave_db
    profiles:
      - donotstart
    networks:
      - mysql_replication

  
  my_pma_source:
    container_name: my_pma_source
    image: phpmyadmin:5.2
    ports:
      - "8080:80"
    depends_on:
      - my_source
    links:
      - my_source:db
    networks:
      - mysql_replication
    profiles:
      - donotstart


  my_pma_replica:
    container_name: my_pma_replica
    image: phpmyadmin:5.2
    ports:
      - "8081:80"
    depends_on:
      - my_replica
    links:
      - my_source:db
    networks:
      - mysql_replication
    profiles:
      - donotstart
    
volumes:
  data_dir:

networks:
  mysql_replication: