version: '3.8'

name: sa_usecase_1_dolt_direct

services:
  dd_primary:
    container_name: dd_primary
    build:
      context: .
      dockerfile: ./direct/primary/Dockerfile
    ports:
      - "33100:3306"
    networks:
      - direct_replication
    
  dd_standby:
    container_name: dd_standby
    build:
      context: .
      dockerfile: ./direct/standby/Dockerfile
    ports:
      - "33101:3306"
    networks:
      - direct_replication

networks:
  direct_replication: