version: '3.8'

name: sa_usecase_1_dolt_remote

services:
  dr_source:
    container_name: dr_source
    build:
      context: .
      dockerfile: ./remote/source/Dockerfile
      args:
        - PUB_CRED
    ports:
      - "33100:3306"

  
  dr_replica:
    container_name: dr_replica
    build:
      context: .
      dockerfile: ./remote/replica/Dockerfile
      args:
        - PUB_CRED
    ports:
      - "33101:3306"