log_level: info

behavior:
  read_only: true
  autocommit: true
  persistence_behavior: load
  disable_client_multi_statements: false

user:
  name: "nkhartwig"
  password: "tmp"

listener:
  host: 0.0.0.0
  port: 3306
  max_connections: 100
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000
  tls_key: null
  tls_cert: null
  require_secure_transport: null
  allow_cleartext_passwords: null
  socket: null